### ISSUE TITLE
App cannot be started with babel-node

### ISSUE THREAD

**Issue by hwclass** [DCKT/Node-Starter-kit#1]
Dear DCKT,

After cloning and trying to make the app started with your instructions in your README file, I have got the following error. I have downloaded the whole packages that your application needs including babel in global:

npm ERR! Failed at the express-boilerplate@1.0.0 start script.
npm ERR! This is most likely a problem with the express-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls express-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/hwclass/Repos/express-boilerplate
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/hwclass/Repos/express-boilerplate/npm-debug.log
npm ERR! not ok code 0

**Comment by DCKT** [comment]
Hello @hwclass 

Can you show me the npm-debug.log ? I tried to reproduce the issue by cloning then npm install and npm start but it works for me.

Have you tried to run without npm ? Just babel-node server.js ?

**Comment by DCKT** [comment]
Hi @hwclass 
Does it works now ? :)

**Comment by hwclass** [comment]
Hi @DCKT,

When I tried to start the server by typing babel-node server.js, the following lines come into the command line:

/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: /Users/hwclass/Repos/express-boilerplate/app/models/Book.js: Line 9: 'this' is not allowed before super()
   7 |
   8 |   constructor(opt) {

>  9 |     this.title = opt.title;
>      |     ^
>   10 |
>   11 |     return this;
>   12 |   }

**Comment by DCKT** [comment]
Hi @hwclass 
Which version of Babel are you using ?
I'm using the 4.7.16 version and it's work on a fresh cloned project.

**Comment by DCKT** [comment]
Hi @hwclass 
I assume the issue is closed, if not tell me more :)
