### ISSUE TITLE
Hello DCKT

### ISSUE THREAD

**Issue by davesnx** [DCKT/Node-Starter-kit#2]
Hi @DCKT,

I really want to participate on this express-boilerplate. 

I will create a PR and we can discuss some changes/improvements.
- My first proposal is Adding babel-node, also can remove the "use strict".
- The second is to orientate the express into OOP. Creating the Controllers like ES6 Class, inherence from a BaseController.
- The third one, is use import from.
- Create migrations with sequelize.
- Refactor a little the app/Router and the server.js
- Reorder assets/view directories -> switch it into public/
- Use a config.js with all the config global settings and declare a database.js for create the singleton of the connection.
- Create logs for all the application using winston or something like that...
- Also at the end should avoid MVC pattern and go for DDD http://es.slideshare.net/bobholt/ddd-17779078

And a lot of more stuff that can we create.
Say something if you want that I collaborate on this.

Thanks for reading.

**Comment by DCKT** [comment]
Hi @davesnx 

Thanks for your PR, I found some proposal very interesting 
- For babel-node, I used it previously but I prefered to stay on current version of Node.js and use harmony flag for some features. I also like the usage and profit of the strict mode.
- I don't see the profit of using Class for controller so if you have some examples 
- import can be used with the harmony tags
- Absolutly ! It could be great to have migration for each model 
- I don't know what you mean about the refactoring ? Isn't cleaner yet ?
- I prefer the current structure of the folders (matter of taste)
- Great idea, the database singleton is already setup but I think it can be fine to have it in a config file
- Nice idea, have to do it :) 
- I didn't know this pattern, do you have demo code with this pattern ? I

Thanks for contributing :)

**Comment by davesnx** [comment]
The --harmony flags have some limitations that babel-node don't have.

The benefit of using Class for the controllers and any model/service/etc, it's huge. 
Inheritance of parent class, easy to abstract only one method, testeability, reuse, etc...

Refactor the server.js, I mean keep it easy to change. I will show how can be usefull in a PR.

The folder structure goes for taste and it's really good (haha), but the abstraction of the different layers is important.

The DDD pattern means Domain Driven Development, there is a huge patter for big applications... 
If you want to read something about it: https://thelongwayback.wordpress.com/2009/09/18/ddd-the-basics/
But there aren't a lot of examples on node.
The example should be https://github.com/jamuhl/nodeCQRS

Thanks D:
